spring:
  rabbitmq:
    port: 5672
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: AUTH-SERVICE
jwt:
  private-key: classpath:keys/private.pem
  public-key: classpath:keys/public.pem
  iss: "auth.krzywdek19.com"
  expiration: 1800000
  refresh-expiration: 604800000
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka