spring:
  application:
    name: AUTH-SERVICE
jwt:
  private-key: classpath:keys/private.pem
  public-key: classpath:keys/public.pem
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka