spring:
  application:
    name: eureka
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
  client:
    eureka-server-port: 8761
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone:  ${EUREKA_URL}
